### ISSUE TITLE
Possible mistakes in cost functions

### ISSUE THREAD

**Issue by marchcat69** [novak-99/MLPP#12]
Cost::MAEDeriv is wrong. y_hat must be compared with y, but not with zero.
Cost::WassersteinLoss is same as Cost::HingeLoss, but thats are not same.

**Comment by novak-99** [comment]
Hi, 

Thank you for taking the time to find these issues. I have updated the MAEDeriv function and the changes will be visible in the next release of ML++. 

Regarding the Wasserstein Loss, as I understand it, it is expressed as:

-1/n * y_i  * y_hat_i, summed over n. 

and is expressed in the codebase as such. 

Please reply back if you found that I misunderstood what you meant to bring up or that I was inaccurate. 

Thanks.

**Comment by marchcat69** [comment]
About Wassersein Loss - this is my mistake. I thought that I was looking at the code of one function, but in fact, I was looking at the code of another. Your Wasserstein cost function is true. Sorry.

**Comment by novak-99** [comment]
Ah, I see- thanks.
